# Site settings
title:          Bravecompany 기술블로그
description:    "Bravecompany TechTeam blog --ing"
baseurl:        ""
url:            ""
timezone:       "Asia/Seoul"
repository:     ""
author: judy@bravecompany.io
image: '/assets/images/judy.png'
# Google Analytics
#google_analytics: UA—XXXXXXXX-X


collections:
  authors:
    output: true
    permalink: /authors/:path/
  posts:
    permalink: "/posts/:year/:month/:day/:title"
    output : true
  tags:
    permalink: /tags/:path/
    output: true

defaults:
- scope:
    path: _posts
    type: posts
    values:
      layout: post
      image: ""

# Build settings
markdown: kramdown

krandown:
  input: GFM
  highlighter: rouge

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus: judy@bravecompany.io

