# Site settings
title:          Bravecompany 기술블로그
description:    "Bravecompany TechTeam blog --ing"
baseurl:        ""
url:            ""
timezone:       "Asia/Seoul"
repository:     ""
author: judy@bravecompany.io
image: '/images/judy.png'
# Google Analytics
#google_analytics: UA—XXXXXXXX-X

category_list : [techCamp1주차,techCamp2주차,techCamp3주차]

collections:
  authors:
    output: true
    permalink: /authors/:path/

# Build settings
markdown: kramdown

krandown:
  input: GFM
  highlighter: rouge

include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale